server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # To jest kluczowe dla Reacta (SPA):
        # Jak nie znajdziesz pliku, przekieruj do index.html zamiast błędu 404
        try_files $uri $uri/ /index.html;
    }

    # Obsługa błędów
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}